version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb+srv://maa607186:Ohm123456@cluster0.joj2ske.mongodb.net/fueltracker
    depends_on:
      - mongodb
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - app_network       

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - mongo-data:/data/db

networks:
  app_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
